apiVersion: v2
name: tempo
description: Tempo component for Karavel
type: application
version: 0.1.0-SNAPSHOT
appVersion: 1.0.0
maintainers:
  - name: JaneDoe
    email: jane.doe@karavel.io

home: https://grafana.com/oss/tempo
sources:
  - https://github.com/grafana/tempo
  - https://github.com/projectkaravel/platform-component-tempo

annotations:
  karavel.io/dependencies: cert-manager, external-secrets
  prometheus.enable: prometheus
