apiVersion: v2
name: tempo
description: Tempo component for Karavel
type: application
version: 1.0.0
appVersion: 1.2.1
maintainers:
  - name: MatteoJoliveau
    email: matteo.joliveau@mikamai.com

home: https://grafana.com/oss/tempo
sources:
  - https://github.com/grafana/tempo
  - https://github.com/karavel-io/platform-component-tempo

annotations:
  karavel.io/dependencies: grafana
  prometheus.enable: prometheus
  grafana.enable: grafana
