apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tempo.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "tempo.name" . }}
  {{ include "tempo.labels" . | nindent 4}}
data:
  tempo.yaml: |
  {{ tpl (.Files.Get "configs/tempo.yaml") . | nindent 4 }}
