apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: {{ include "tempo.name" . }}-datasource
  namespace: {{ .Values.grafana.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "tempo.name" . }}
    grafana.integreatly.org/instance: grafana-operated
  {{- include "tempo.labels" . | nindent 4 }}
spec:
  name: tempo.yaml
  datasources:
    - name: {{ title (include "tempo.name" . ) }}
      type: tempo
      uid: {{ include "tempo.name" . }}
      access: proxy
      url: http://{{ include "tempo.name" . }}.{{ .Release.Namespace }}:3200
      version: 1
      editable: false
