apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "tempo.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "tempo.name" . }}
    {{- include "tempo.labels" . | nindent 4 }}
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "tempo.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "tempo.name" . }}
    {{- include "tempo.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: RoleBinding
  name: {{ include "tempo.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "tempo.name" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tempo.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "tempo.name" . }}
    {{- include "tempo.labels" . | nindent 4 }}
