apiVersion: v1
kind: Service
metadata:
  name: {{ include "tempo.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "tempo.name" . }}
  {{ include "tempo.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "tempo.name" . }}
  {{ include "tempo.selectorLabels" . | nindent 4 }}
  type: ClusterIP
  ports:
    - name: tempo
      port: 3200
      targetPort: tempo
    - name: jaeger-compact
      port: 6831
      targetPort: jaeger-compact
    - name: jaeger-binary
      port: 6832
      targetPort: jaeger-binary
    - name: jaeger-http
      port: 14268
      targetPort: jaeger-http
    - name: jaeger-grpc
      port: 14250
      targetPort: jaeger-grpc
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
    - name: zipkin
      port: 9411
      targetPort: zipkin
