apiVersion: v1
kind: Service
metadata:
  name: {{ include "example.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "example.name" . }}
    {{- include "example.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "example.name" . }}
    {{- include "example.selectorLabels" . | nindent 4 }}
