apiVersion: v1
kind: Service
metadata:
  name: {{ include "tempo.name" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "tempo.name" . }}
    app.kubernetes.io/service: headless
  {{- include "tempo.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: 3200
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
    - port: 7946
      protocol: TCP
      name: gossip
      targetPort: gossip
    - name: grpclb
      port: 9096
      targetPort: tempo-query
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "tempo.name" . }}
  {{- include "tempo.selectorLabels" . | nindent 4 }}
